if [ "$RELEASE" = "" ]; then
  RELEASE=$(cat RELEASE)
fi;

OPT_FLAGS=" "
if [ "$RELEASE" = "1" ]; then
  OPT_FLAGS=$(cat release.flags)" "
else
  OPT_FLAGS=$(cat debug.flags)" "
fi

echo "Release Mode (0/1): "$RELEASE
echo "Mode Flags: "$OPT_FLAGS
sleep 0.115
EMSTACKDEBUG=0
EMMETHODLOGS=0
EMSTATICCALLLOGS=0

PROJ_ROOT=$(pwd)
export SOURCE_DATE_EPOCH=315532802
EMSTACKSIZE=$((16 * 1024 * 1024))
MEMMB=2048
EMMEMPG=$((($MEMMB * 1024 * 1024 / 64) * 64))
EMTHREADPOOL=10
cd runner
mkdir -p emcache
export EMCACHE=$(pwd)"/emcache"
cd ../docs
unlink make/hotspot
rm -rf *
echo $(pwd)
emcc ../runner/main.cpp -Wl,--whole-archive ../wasmjdk_build/monolith/libjvm.a -Wl,--no-whole-archive -Wl,--whole-archive -L../libffi/wasm_build/lib/ -lffi -I../libffi/wasm_build/include/  -I../patch_include/ -pthread -I../wasmjdk_build/monolith/include/ -I../wasmjdk_build/monolith/include/linux/ -o jvm.js $(cat ../export.flags) -sINVOKE_RUN=0 -fdebug-compilation-dir='.' --emit-symbol-map --profiling-funcs -fstandalone-debug -pthread -sUSE_PTHREADS=1 -sSHARED_MEMORY=1 -Wl,--error-limit=0 -ferror-limit=0 -sSEPARATE_DWARF_URL="jvm.wasm.debug.wasm" \
 -s MODULARIZE=1 -s EXPORT_NAME='initJVM' \
 -sERROR_ON_UNDEFINED_SYMBOLS=0 -sALLOW_MEMORY_GROWTH=0 -sMAIN_MODULE -sRELOCATABLE=1 -sEXPORT_ALL=1 -sLINKABLE=1 -Wl,--export-dynamic -Wl,--allow-multiple-definition -sINITIAL_MEMORY=$EMMEMPG -sMAXIMUM_MEMORY=$EMMEMPG \
 -sSTACK_SIZE=$EMSTACKSIZE -sDEFAULT_PTHREAD_STACK_SIZE=$EMSTACKSIZE -sWASM_BIGINT=1 -sSTACK_OVERFLOW_CHECK=1 -sPTHREAD_POOL_SIZE=$EMTHREADPOOL -sPTHREAD_POOL_SIZE_STRICT=2 \
 -sFILESYSTEM=1 $OPT_FLAGS

mkdir -p make
ln -s ../../jdk/ ./make/hotspot
cp ../runner/template/* .

rm -r ../runner/test/compiled
mkdir -p ../runner/test/compiled
cd ../runner/test

echo "#autogenerated, do not manually edit" > tests.txt

find . -type f -name "*.java" | while read file
do
  echo "Compiling test: $file"
  FDIR=$(dirname "$file")
  DIR=$FDIR
  FDIR=$(echo "${FDIR##*/}")
  javac $file
  mv $DIR"/Main.class" ./compiled/$FDIR.class
  echo $FDIR >> tests.txt
done

cp -r compiled/ ../../docs/compiled_tests
cp tests.txt ../../docs/tests.txt

echo "Copying runtime..."
cd $PROJ_ROOT"/docs"
mkdir -p rt
cp ../wasmjdk_build/runtime/release rt/rt.info
echo "" >> rt/rt.info
echo "BUILD_HOST=\""$(uname)" "$(uname -r)" "$(uname -m)" "$USER"@"$(uname -n)"\"" >> rt/rt.info
cp ../wasmjdk_build/runtime/lib/modules rt/modules
echo "Done!"
