PROJ_ROOT=$(pwd)
export SOURCE_DATE_EPOCH=315532802
cd runner
mkdir -p emcache
export EMCACHE=$(pwd)"/emcache"
cd ../docs
unlink make/hotspot
unlink make/src
rm -rf *
echo $(pwd)
emcc ../runner/main.cpp ../wasmjdk_build/monolith/libjvm.a -sLIBRARY_DEBUG=1 -L../libffi/wasm_build/lib/ -lffi -I../libffi/wasm_build/include/ -pthread -I../wasmjdk_build/monolith/include/ -I../wasmjdk_build/monolith/include/linux/ -o jvm.js $(cat ../export_flags) -g4 -O0 -gsource-map -gseparate-dwarf -sINVOKE_RUN=0 -fdebug-compilation-dir='.' --emit-symbol-map --profiling-funcs -fstandalone-debug -pthread -sUSE_PTHREADS=1 -sSHARED_MEMORY=1 -Wl,--error-limit=0 -ferror-limit=0 -sSEPARATE_DWARF_URL="jvm.wasm.debug.wasm" \
 -s MODULARIZE=1 -s EXPORT_NAME='initJVM' \
 -s ALLOW_MEMORY_GROWTH=0 -s TOTAL_MEMORY=2147483648 --debug -fPIC

mkdir -p make
ln -s ../../jdk/ ./make/hotspot
ln -s ../../jdk/src/ ./make/src
cp ../runner/template/* .

rm -r ../runner/test/compiled
mkdir -p ../runner/test/compiled
cd ../runner/test

echo "#autogenerated, do not manually edit" > tests.txt

find . -type f -name "*.java" | while read file
do
  echo "Compiling test: $file"
  FDIR=$(dirname "$file")
  DIR=$FDIR
  FDIR=$(echo "${FDIR##*/}")
  javac $file
  mv $DIR"/Main.class" ./compiled/$FDIR.class
  echo $FDIR >> tests.txt
done

cp -r compiled/ ../../docs/compiled_tests
cp tests.txt ../../docs/tests.txt

echo "Copying runtime..."
cd $PROJ_ROOT"/docs"
mkdir -p rt
cp ../wasmjdk_build/runtime/release rt/rt.info
cp ../wasmjdk_build/runtime/lib/modules rt/modules
cd $PROJ_ROOT
./llvm_visibility_scanner.sh docs/jvm.wasm
echo "Done!"
